report

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -6,45 +6,137 @@
 os=`uname -s`
 
 # Figure out C compiler.
-# We can probably assume gcc is available, so it's the failsafe.
+
 printf "checking for C compiler... "
-/usr/bin/which cc > /dev/null 2>&1
+/usr/bin/which clang > /dev/null 2>&1
 if [ $? -eq 0 ] ; then
-    cc="cc"
+    cc="clang"
 else
-    /usr/bin/which clang > /dev/null 2>&1
-    if [ $? -eq 0 ] ; then
-	cc="clang"
+    # The bounded strings used by ohash are not available in mainstream GCC, but
+    # it is in mainstream Clang. The detecting script is a bit unsightly but
+    # everything seems to store clang in weird places under bizarre names. We
+    # also have to filter out all the extra clang tools that pop up. Try to use
+    # the newest version if multiple are found.
+    cat /dev/null > /tmp/clanglist
+    for f in `echo ${PATH} | sed 's/:/ /g'`
+    do
+	ls -1 ${f} | grep clang[-_0-9] | grep -v -e '-cpp'			\
+	    -e '-apply-replacements'  -e '-change-namespace' -e '-check'	\
+	    -e '-cl' -e '-doc' -e '-extdef-mapping' -e '-include-fixer'		\
+	    -e '-move' -e '-offload-bundler' -e '-offload-wrapper'  -e '-query' \
+	    -e '-refactor' -e '-rename' -e '-reorder-fields' -e '-scan-deps'	\
+	    -e '-tidy' >> /tmp/clanglist
+    done
+    CLANG=$(sort /tmp/clanglist | tail -n1)
+    if [ ! -z "${CLANG}" ] ; then
+	cc="${CLANG}"
     else
-	/usr/bin/which gcc > /dev/null 2>&1
+	/usr/bin/which cc > /dev/null 2>&1
 	if [ $? -eq 0 ] ; then
-	    cc="gcc"
+	    cc="cc"
 	else
-	    echo "not found"
-	    echo "Please put cc, clang, or gcc in your $PATH"
-	    exit 1
+	    # We can probably assume gcc is available, so it's the failsafe.
+	    /usr/bin/which gcc > /dev/null 2>&1
+	    if [ $? -eq 0 ] ; then
+		cc="gcc"
+	    fi
 	fi
     fi
+    rm /tmp/clanglist
 fi
+if [ -z "${cc}" ] ; then
+    echo "not found"
+    echo "Please put cc, clang, or gcc in your $PATH"
+    exit 1
+fi
+
 echo "$cc"
+
+printf "checking if compiler supports bounded functions..."
+cat << EOF > /tmp/checkbounded.c
+/* This file generated by omake configure script.  */
+void __attribute__((__bounded__(__buffer__, 1, 2)))
+checkbound(char *str, int size)
+{
+
+};
+
+int
+main()
+{
+	checkbound("foo", 4);
+
+	return 0;
+}
+EOF
+$cc -o /tmp/checkbounded /tmp/checkbounded.c
+
+if [ $? -eq 0 ] ; then
+    DHB="-DHAVE_BOUNDED"
+    echo "yes"
+else
+    echo "no"
+fi
+
 
 # What will we call make and where will it live?
 printf "determining full path and name for omake... "
 /usr/bin/which /usr/bin/make > /dev/null 2>&1
+if [ ! -z "${PREFIX}" ] ; then
+    prefix="${PREFIX}"
+fi
+if [ ! -z "${NAME}" ] ; then
+    omake="${NAME}"
+fi
+
 if [ $? -ne 0 ] ; then
-    omake="make"
-    prefix="/usr"
+    if [ -z ${omake} ] ; then
+	omake="make"
+    fi
+    if [ -z "${prefix}" ] ; then
+	prefix="/usr"
+    fi
 else
     /usr/bin/which /usr/local/bin/make > /dev/null 2>&1
-    if [ $? -ne 0 ] ; then
-	omake="make"
-    else
-	omake="omake"
+    if [ -z ${omake} ] ; then
+	if [ $? -ne 0 ] ; then
+	    omake="make"
+	else
+	    omake="omake"
+	fi
     fi
-	prefix="/usr/local"
-	DSP="-D_PATH_DEFSYSPATH=\"\\\"$prefix/share/mk\\\"\""
+    if [ -z "${prefix}" ] ; then
+	 prefix="/usr/local"
+    fi
+    DSP="-D_PATH_DEFSYSPATH=\\"\"$prefix/share/mk\\"\""
 fi
 echo "$prefix/bin/$omake"
+
+printf "checking for arc4random... "
+cat << EOF > /tmp/checkarc4random.c
+/* This file generated by omake configure script.  */
+
+#include <stdlib.h>
+
+int
+main(void)
+{
+	(void) arc4random(256);
+
+	return 0;
+}
+EOF
+
+$cc -o /tmp/checkarc4random /tmp/checkarc4random.c > /dev/null 2>&1
+
+if [ $? -ne 0 ] ; then
+    DNA4R="-DNEED_ARC4RANDOM_UNIFORM"
+    echo "no"
+else
+    echo "yes"
+fi
+
+rm -f /tmp/checkarc4random /tmp/checkarc4random.c checkarc4random.o
 
 printf "checking for asprintf... "
 cat << EOF > /tmp/checkasprintf.c
@@ -57,7 +149,7 @@ main(void)
 {
 	char *tmp = "y";
 
-	(void) asprintf(NULL, "%s\n", tmp);
+	(void) asprintf(NULL, "%s\\n", tmp);
 
 	return 0;
 }
@@ -99,6 +191,86 @@ else
 fi
 
 rm -f /tmp/checkfgetln /tmp/checkfgetln.c checkfgetln.o
+
+printf "checking for optreset... "
+cat << EOF > /tmp/checkoptreset.c
+/* This file generated by omake configure script.  */
+
+#include <unistd.h>
+
+int
+main(void)
+{
+	optreset = 1;
+
+	return optreset ? 0 : 1;
+}
+EOF
+
+$cc -o /tmp/checkoptreset /tmp/checkoptreset.c > /dev/null 2>&1
+
+if [ $? -ne 0 ] ; then
+    DNO="-DNEED_OPTRESET"
+    echo "no"
+else
+    echo "yes"
+fi
+
+rm -f /tmp/checkoptreset /tmp/checkoptreset.c checkoptreset.o
+
+printf "checking for pledge... "
+cat << EOF > /tmp/checkpledge.c
+/* This file generated by omake configure script.  */
+
+#include <unistd.h>
+
+int
+main(void)
+{
+	(void) pledge("stdio", NULL);
+
+	return 0;
+}
+EOF
+
+$cc -o /tmp/checkpledge /tmp/checkpledge.c > /dev/null 2>&1
+
+if [ $? -ne 0 ] ; then
+    DNPL="-DNEED_PLEDGE"
+    echo "no"
+else
+    echo "yes"
+fi
+
+rm -f /tmp/checkpledge /tmp/checkpledge.c checkpledge.o
+
+printf "checking for __progname... "
+cat << EOF > /tmp/checkprogname.c
+/* This file generated by omake configure script.  */
+
+#include <stdio.h>
+
+extern char *__progname;
+
+int
+main(void)
+{
+	(void) fprintf(stderr, "%s\\n", __progname);
+
+	return 0;
+}
+EOF
+
+$cc -o /tmp/checkprogname /tmp/checkprogname.c > /dev/null 2>&1
+
+if [ $? -ne 0 ] ; then
+    DNP="-DNEED_PROGNAME"
+    echo "no"
+else
+    echo "yes"
+fi
+
+rm -f /tmp/checkprogname /tmp/checkprogname.c checkprogname.o
 
 printf "checking for reallocarray... "
 cat << EOF > /tmp/checkreallocarray.c
@@ -182,33 +354,6 @@ fi
 
 rm -f /tmp/checkstrtonum /tmp/checkstrtonum.c checkstrtonum.o
 
-printf "checking for __progname... "
-cat << EOF > /tmp/checkprogname.c
-/* This file generated by omake configure script.  */
-
-#include <stdio.h>
-
-extern char *__progname;
-
-int
-main(void)
-{
-	(void) fprintf(stderr, "%s\n", __progname);
-
-	return 0;
-}
-EOF
-
-$cc -o /tmp/checkprogname /tmp/checkprogname.c > /dev/null 2>&1
-
-if [ $? -ne 0 ] ; then
-    DNP="-DNEED_PROGNAME"
-    echo "no"
-else
-    echo "yes"
-fi
-
-rm -f /tmp/checkprogname /tmp/checkprogname.c checkprogname.o
 
 if [ "x$os" = "xOpenBSD" ] ; then
     cflags="-O2 -pipe -std=c99"
@@ -223,7 +368,8 @@ elif [ "x$os" = "xDragonFly" ] ; then
 elif [ "x$os" = "xDarwin" ] ; then
     cflags="-O2 -pipe -std=c99"
 elif [ "x$os" = "xLinux" ] ; then
-    cflags="-O2 -pipe -std=c99 -D_GNU_SOURCE -D_BSD_SOURCE"
+    cflags="-O2 -pipe -std=c99 -D_GNU_SOURCE -D_DEFAULT_SOURCE"
+    cflags=" -Dst_mtimensec=st_mtim.tv_nsec -DNEED_SYS_SIGNAME"
 elif [ "x$os" = "xSunOS" ] ; then
     if [ "x$CC" = "xgcc" ] ; then
 	cflags="-O2 -pipe -std=c99"
@@ -253,20 +399,20 @@ cat << EOF > Makefile
 PREFIX=	$prefix
 
 CC=	$cc
-CFLAGS=	$cflags $DSP
+CFLAGS=	$cflags $DSP $DNPL $DNO
 CFLAGS+=-I. -DHAS_PATHS_H -DHAS_EXTENDED_GETCWD
-CFLAGS+=$DNA $DNF $DNP $DNR $DNS $DNSTN
+CFLAGS+=$DHB $DNA $DNF $DNP $DNR $DNS $DNSTN $DNSTMN $DNA4R
 
 PROG=	$omake
-OBJS=	arch.o buf.o cmd_exec.o compat.o cond.o dir.o direxpand.o dump.o \\
-	engine.o error.o for.o init.o job.o lowparse.o main.o make.o \\
-	memory.o ohash.o parse.o parsevar.o portable.o str.o stats.o suff.o \\
-	targ.o targequiv.o timestamp.o var.o varmodifiers.o varname.o \\
-	lstAddNew.o lstAppend.o lstConcat.o lstConcatDestroy.o lstDeQueue.o \\
-	lstDestroy.o lstDupl.o lstFindFrom.o lstForEachFrom.o lstInsert.o \\
-	lstMember.o lstRemove.o lstReplace.o lstRequeue.o lstSucc.o
+OBJS=	arch.o buf.o cmd_exec.o compat.o cond.o dir.o direxpand.o dump.o        \\
+	engine.o enginechoice.o error.o expandchildren.o for.o init.o job.o     \\
+	lowparse.o main.o make.o memory.o ohash.o parse.o parsevar.o portable.o \\
+	str.o stats.o suff.o targ.o targequiv.o timestamp.o var.o varmodifiers.o\\
+	varname.o lstAddNew.o lstAppend.o lstConcat.o lstConcatDestroy.o        \\
+	lstDeQueue.o lstDestroy.o lstDupl.o lstFindFrom.o lstForEachFrom.o      \\
+	lstInsert.o lstMember.o lstRemove.o lstReplace.o lstRequeue.o lstSucc.o
 
-all: generate varhashconsts.h condhashconsts.h nodehashconsts.h \${OBJS}
+all:	generate varhashconsts.h condhashconsts.h nodehashconsts.h \${OBJS}
 	\${CC} \${LDFLAGS} -o \${PROG} \${OBJS}
 
 install: all
@@ -276,7 +422,7 @@ install: all
 	install -c -s -m 555 \${PROG} \${PREFIX}/bin
 	install -c -m 444 make.1 \${PREFIX}/man/man1/\${PROG}.1
 	install -c -m 444 mk/bsd.dep.mk \${PREFIX}/share/mk
-	install -c -m 444 mk/bsd.lib.mk \${PREFIX}/share/mk
+	install -c -m 444 mk/bsd.lib.mk \${PREFIX}/share/mkb
 	install -c -m 444 mk/bsd.man.mk \${PREFIX}/share/mk
 	install -c -m 444 mk/bsd.obj.mk \${PREFIX}/share/mk
 	install -c -m 444 mk/bsd.own.mk \${PREFIX}/share/mk
@@ -305,7 +451,39 @@ nodehashconsts.h:
 	./generate 3 0 >\$@.tmp && mv \$@.tmp \$@
 
 generate:
-	\${CC} \${CFLAGS} \${LDFLAGS} -o \$@ generate.c stats.c memory.c ohash.c portable.c
+	\${CC} \${CFLAGS} \${LDFLAGS} -o \$@ generate.c stats.c memory.c ohash.c   \\
+	portable.c
+
+lstAddNew.o:
+	\${CC} \${CFLAGS} \${LDFLATS} -c lst.lib/lstAddNew.c -o lstAddNew.o
+lstAppend.o:
+	\${CC} \${CFLAGS} \${LDFLAGS} -c lst.lib/lstAppend.c -o lstAppend.o
+lstConcat.o:
+	\${CC} \${CFLAGS} \${LDFLAGS} -c lst.lib/lstConcat.c -o lstConcat.o
+lstConcatDestroy.o:
+	\${CC} \${CFLAGS} \${LDFLAGS} -c lst.lib/lstConcatDestroy.c -o lstConcatDestroy.o
+lstDeQueue.o:
+	\${CC} \${CFLAGS} \${LDFLAGS} -c lst.lib/lstDeQueue.c -o lstDeQueue.o
+lstDestroy.o:
+	\${CC} \${CFLAGS} \${LDFLAGS} -c lst.lib/lstDestroy.c -o lstDestroy.o
+lstDupl.o:
+	\${CC} \${CFLAGS} \${LDFLAGS} -c lst.lib/lstDupl.c -o lstDupl.o
+lstFindFrom.o:
+	\${CC} \${CFLAGS} \${LDFLAGS} -c lst.lib/lstFindFrom.c -o lstFindFrom.o
+lstForEachFrom.o:
+	\${CC} \${CFLAGS} \${LDFLAGS} -c lst.lib/lstForEachFrom.c -o lstForEachFrom.o
+lstInsert.o:
+	\${CC} \${CFLAGS} \${LDFLAGS} -c lst.lib/lstInsert.c -o lstInsert.o
+lstMember.o:
+	\${CC} \${CFLAGS} \${LDFLAGS} -c lst.lib/lstMember.c -o lstMember.o
+lstRemove.o:
+	\${CC} \${CFLAGS} \${LDFLAGS} -c lst.lib/lstRemove.c -o lstRemove.o
+lstReplace.o:
+	\${CC} \${CFLAGS} \${LDFLAGS} -c lst.lib/lstReplace.c -o lstReplace.o
+lstRequeue.o:
+	\${CC} \${CFLAGS} \${LDFLAGS} -c lst.lib/lstRequeue.c -o lstRequeue.o
+lstSucc.o:
+	\${CC} \${CFLAGS} \${LDFLAGS} -c lst.lib/lstSucc.c -o lstSucc.o
 
 CKOBJS=	regress.o str.o memory.o buf.o ohash.o portable.o
 
@@ -318,7 +496,8 @@ regress: check
 test: regress
 
 clean:
-	rm -f \${PROG} \${OBJS} generate varhashconsts.h condhashconsts.h nodehashconsts.h check \${CKOBJS}
+	rm -f \${PROG} \${OBJS} generate varhashconsts.h condhashconsts.h \\
+	    nodehashconsts.h check \${CKOBJS}
 
 distclean: clean
 	rm -f Makefile
